--- # Application configuration - config.yaml
pipeline_config:
    # Dataset
    input_train_img_folder: "data/Furnas_Image_Segmentation_Dataset/imgs/train/"
    input_test_img_folder: "data/Furnas_Image_Segmentation_Dataset/imgs/test/"
    input_train_csv: "data/Furnas_Image_Segmentation_Dataset/data/train.json"
    input_test_csv: "data/Furnas_Image_Segmentation_Dataset/data/test.json"
    train_record_path: "data/Furnas_Image_Segmentation_Dataset/train.record"
    test_record_path: "data/Furnas_Image_Segmentation_Dataset/test.record"
    labelmap_path: "data/Furnas_Image_Segmentation_Dataset/data/label_map.pbtxt"
    image_extension: "jpg"
    classes_names: "['torre']"
    # Model
    model_name: "mask_rcnn_inception_resnet_v2_1024x1024"
    checkpoint_save_path: "checkpoints"
    pipeline_config_filepath: "data/pipeline_mask_rcnn_inception_resnet_v2_1024x1024.config"
    # Training
    num_train_steps: 10000
    checkpoint_every_n: 10000
    batch_size: 1 # 75 for 15G GPU
    use_data_aug: false # True or False
